AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - spec/*
    - demo/*

Style/RegexpLiteral:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - qrcode_pix_ruby.gemspec

Metrics/MethodLength:
  Max: 20

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
