name: CI

on: [push, pull_request]

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Dockerfile
        run: docker build -t qrcode_pix_ruby_specs .

      - name: Run tests inside Docker container
        run: docker run -v $(pwd):/app/ -i qrcode_pix_ruby_specs
          
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7, 3.0]
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Update rubygems
        run: gem update --system

      - name: Install dependencies
        run: bundle install

      - name: Run tests with Ruby ${{ matrix.ruby-version }}
        run: bundle exec rake
